### ISSUE TITLE
Redirect to Signin page (hosted UI)

### ISSUE THREAD

**Issue by zsan** [fernando-mc/aws-http-api-python-cognito#1]
Hi @fernando-mc ,

I think this is more to question rather than an issue, i am sorry for that :).

As far as i know, there is no way to redirect user to `signin page` or `hosted UI login` (when user has no access to the protected page), is that correct ?

Regards,
Zak

**Comment by fernando-mc** [comment]
Hi Zak,

I think the user can be redirected after using the signing page? I assume it's also possible with the hosted UI but I haven't done a ton of work with it. I'd suggest adding some detail and tossing the question in the AWS Reddit or one of the AWS Slack groups to try and get more attention on it from someone who knows Cognito better than I do.

Sorry I can't help more!

**Comment by zsan** [comment]
Hi Fernando,

For example, 
I have a page and the page is only for authenticated users, for example `/admins/config`.
And so my handler will return `{"message":"Unauthorized"}` when unauthenticated users visit the page directly.
What I am trying to do is to redirect users to the login page instead return `{"message":"Unauthorized"}` ..

But thanks anyway, i think i will just switch to AWS RestAPI .. i'll switch to another github's repo which is yours i guess ..
https://github.com/fernando-mc/serverless-learn-serverlessjams

**Comment by fernando-mc** [comment]
I think you can do that, it just depends on how you implement it? The frontend could see the Unauthorized response and generate the error message more appropriately. I use Auth0 more commonly than I use Cognito to be honest precisely because they have examples fo doing this sort of thing.

In the Auth0 examples (if you go that route) I think you can find a helper somewhere called "authGuard.js" which I think helps redirect folks. That might have been specific to a vue.js frontend but they should have options for similar things with other frontend tools.
